In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [7]:
df.shape

(5572, 3)

In [8]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [11]:
X_train.shape

(4457,)

In [12]:
X_test.shape

(1115,)

In [15]:
X_train[:4]

4879    No 1 POLYPHONIC tone 4 ur mob every week! Just...
2126    Sorry im getting up now, feel really bad- tota...
3203    Okay lor... Wah... like that def they wont let...
1917    Fffff. Can you text kadeem or are you too far ...
Name: Message, dtype: object

In [16]:
type(X_train)

pandas.core.series.Series

In [17]:
type(y_train)

pandas.core.series.Series

In [18]:
y_train[:4]

4879    1
2126    0
3203    0
1917    0
Name: spam, dtype: int64

In [20]:
type(X_train.values)

numpy.ndarray

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59211 stored elements and shape (4457, 7716)>

In [27]:
X_train_cv.toarray()[:4][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
X_train_cv.shape

(4457, 7716)

In [31]:
v.get_feature_names_out().shape #Phương thức này lấy danh sách tất cả các từ (features) mà CountVectorizer đã học được từ tập dữ liệu X_train

(7716,)

In [32]:
v.vocabulary_

{'no': 4775,
 'polyphonic': 5278,
 'tone': 6933,
 'ur': 7170,
 'mob': 4525,
 'every': 2647,
 'week': 7414,
 'just': 3859,
 'txt': 7061,
 'pt2': 5463,
 'to': 6906,
 '87575': 688,
 '1st': 325,
 'free': 2958,
 'so': 6257,
 'get': 3099,
 'txtin': 7066,
 'now': 4822,
 'and': 946,
 'tell': 6726,
 'friends': 2982,
 '150p': 294,
 '16': 302,
 'reply': 5692,
 'hl': 3429,
 '4info': 507,
 'sorry': 6305,
 'im': 3596,
 'getting': 3106,
 'up': 7153,
 'feel': 2780,
 'really': 5587,
 'bad': 1182,
 'totally': 6965,
 'rejected': 5649,
 'that': 6778,
 'kinda': 3931,
 'me': 4391,
 'thing': 6810,
 'okay': 4894,
 'lor': 4194,
 'wah': 7323,
 'like': 4098,
 'def': 2199,
 'they': 6806,
 'wont': 7551,
 'let': 4074,
 'us': 7184,
 'go': 3140,
 'haha': 3271,
 'what': 7450,
 'did': 2279,
 'say': 5897,
 'in': 3624,
 'the': 6782,
 'terms': 6742,
 'conditions': 1940,
 'fffff': 2796,
 'can': 1612,
 'you': 7676,
 'text': 6756,
 'kadeem': 3870,
 'or': 4953,
 'are': 1033,
 'too': 6943,
 'far': 2752,
 'gone': 3158,
 'urgh':

In [47]:
v.get_feature_names_out()[946]

'and'

In [48]:
X_train_np = X_train_cv.toarray() #chuyển từ mảng thưa sang mảng numpy
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [49]:
np.where(X_train_np[0] != 0)

(array([ 294,  302,  325,  507,  688,  946, 2647, 2958, 2982, 3099, 3429,
        3859, 4525, 4775, 4822, 5278, 5463, 5692, 6257, 6726, 6906, 6933,
        7061, 7066, 7170, 7414], dtype=int64),)

In [50]:
X_train[:4][4879]

'No 1 POLYPHONIC tone 4 ur mob every week! Just txt PT2 to 87575. 1st Tone FREE ! so get txtin now and tell ur friends. 150p/tone. 16 reply HL 4info'

In [51]:
X_train_np[0][325]

1

In [52]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [53]:
X_test_cv = v.transform(X_test)

In [54]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       971
           1       0.96      0.94      0.95       144

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [55]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [59]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb',MultinomialNB())
])

In [60]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [63]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       971
           1       0.96      0.94      0.95       144

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

